# SPDX-FileCopyrightText: 2023-2026 KUNBUS GmbH
#
# SPDX-License-Identifier: MIT

include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/package-devel.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/reuse-lint.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/check-commit/lint-commit.yml"
  - project: revolutionpi/infrastructure/ci-templates
    file: coverity-submit.yml
  - project: revolutionpi/infrastructure/ci-templates
    file: create-pristine-tar.yml
  - local: debian/gitlab-ci.yml
    rules:
      - exists:
          - debian/gitlab-ci.yml

variables:
  SRCPKG_NAME: pitest

coverity-submit:
  before_script:
    - apt update
    - apt-get build-dep -y pitest
    - cmake -Bbuild .
    - export BUILD_CMD="cmake --build build"
