# SPDX-FileCopyrightText: 2026 KUNBUS GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later
---
include:
  - project: revolutionpi/infrastructure/ci-templates
    file: package-deb.yml
  - project: revolutionpi/infrastructure/ci-templates
    file: package-release-debian.yml

build-package:
  parallel:
    matrix:
      - ARCH: [arm64]
        RELEASE: trixie
